import Foundation

nonisolated extension RemoteTmuxCommandBuilder {
    private static func windowsConfigLines(
        terminalType: RemoteTerminalType,
        themeStyle: RemoteSessionThemeStyle
    ) -> [String] {
        // psmux runs one server per session. VVTerm loads this global-looking
        // config only into the explicitly targeted managed-session server.
        let theme = themeStyle
        var lines = [
            "# VVTerm tmux configuration",
            "# Auto-generated by VVTerm - changes will be overwritten",
            "",
            "set -g @vvterm-managed 1",
            "",
            "# Preserve true-color and terminal metadata when attaching",
        ]
        lines.append(contentsOf: RemoteTerminalBootstrap.tmuxArrayOptionCommands(
            option: "update-environment",
            values: RemoteTerminalBootstrap.tmuxUpdateEnvironmentVariables()
        ))
        lines.append(contentsOf: RemoteTerminalBootstrap.tmuxEnvironmentCommands())
        lines.append(contentsOf: RemoteTerminalBootstrap.tmuxArrayOptionCommands(
            option: "terminal-features",
            values: ["*:hyperlinks"]
        ))
        lines.append(contentsOf: RemoteTerminalBootstrap.tmuxArrayOptionCommands(
            option: "terminal-overrides",
            values: ["\(terminalType.rawValue):RGB"]
        ))
        lines.append(contentsOf: [
            "",
            "# Allow OSC sequences to pass through (title updates, etc.)",
            "set -g allow-passthrough on",
            "",
            "# Publish the active pane title to the outer VVTerm terminal"
        ])
        lines.append(contentsOf: titlePropagationConfigLines())
        lines.append(contentsOf: [
            "",
            "# Hide status bar",
            "set -g status off",
            "",
            "# Increase scrollback buffer",
            "set -g history-limit 10000",
            "",
            "# Enable mouse support",
            "set -g mouse on",
            "",
            "# Set default terminal with true color support",
            "set -g default-terminal \"\(terminalType.rawValue)\"",
            "",
            "# Selection highlighting in copy-mode (from theme: \(theme.name))",
            "set -g mode-style \"\(theme.modeStyle)\""
        ])

        lines.append(contentsOf: [
            "",
            "# Use psmux's native scroll behavior on Windows"
        ])

        return lines
    }

    static func separateManagedConfigurationCommand(
        themeStyle: RemoteSessionThemeStyle,
        backend: RemoteTmuxBackend
    ) -> String? {
        // Windows OpenSSH's PTY command buffer is limited to 8,191 characters
        // even with PowerShell. Keep setup out of the encoded launch command.
        guard backend.isWindows else { return nil }
        return windowsShellCommand(
            powerShellScript: windowsConfigWritePowerShell(
                terminalType: RemoteTerminalBootstrap.defaultTerminalType,
                themeStyle: themeStyle, backend: backend
            ),
            backend: backend
        )
    }

    private static func windowsConfigWritePowerShell(
        terminalType: RemoteTerminalType,
        themeStyle: RemoteSessionThemeStyle,
        backend: RemoteTmuxBackend
    ) -> String {
        let lines = windowsConfigLines(
            terminalType: terminalType,
            themeStyle: themeStyle
        )
        // This script also travels through cmd.exe's limited command line.
        // Configuration comments and blank lines need not be sent to the host.
        let content = lines.filter { !$0.isEmpty && !$0.hasPrefix("#") }
            .joined(separator: "\n") + "\n"
        let defaultShellExpression: String?
        switch backend.shellFamily {
        case .powershell:
            defaultShellExpression = "[System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName"
        case .cmd:
            defaultShellExpression = "$env:ComSpec"
        case .unknown, .posix, nil:
            defaultShellExpression = nil
        }
        // This config is sourced again on reconnect. `-o` keeps this a one-time
        // choice for the VVTerm-managed psmux server.
        let defaultShellConfiguration = defaultShellExpression.map { expression in
            """
            $vvtermDefaultShell = \(expression)
            $vvtermDefaultShell = $vvtermDefaultShell.Replace('\\', '/')
            $vvtermConfigContent += "`n# Match the shell used by the VVTerm SSH connection`n"
            $vvtermConfigContent += "set -o default-shell `"$vvtermDefaultShell`"`n"
            """
        } ?? ""
        return """
        $vvtermConfigDirectory = \(windowsConfigDirectoryPowerShellExpression())
        $vvtermConfigPath = \(windowsConfigPathPowerShellExpression())
        New-Item -ItemType Directory -Force -Path $vvtermConfigDirectory -ErrorAction Stop | Out-Null
        $vvtermConfigContent = @'
        \(content)'@
        \(defaultShellConfiguration)
        $vvtermConfigContent | Set-Content -Encoding UTF8 -NoNewline -Path $vvtermConfigPath -ErrorAction Stop
        """
    }

    static func windowsInstallAndAttachScript(
        sessionName: String,
        workingDirectory: String,
        terminalType: RemoteTerminalType,
        themeStyle: RemoteSessionThemeStyle,
        backend: RemoteTmuxBackend,
        attachAfterInstall: Bool
    ) -> String {
        let configWrite = windowsConfigWritePowerShell(
            terminalType: terminalType,
            themeStyle: themeStyle,
            backend: backend
        )
        let attach = windowsEnsureManagedPowerShell(
            sessionName: sessionName,
            workingDirectory: workingDirectory,
            backend: backend,
            themeStyle: themeStyle,
            commandExpression: "$vvtermPsmuxCommand.Source"
        )
        let afterInstall = attachAfterInstall ? attach : "Write-Output 'psmux installation completed.'"
        let script = """
        \(configWrite)
        function Get-VVTermPsmuxCommand {
          $cmd = Get-Command psmux -ErrorAction SilentlyContinue
          if (-not $cmd) {
            $cmd = Get-Command pmux -ErrorAction SilentlyContinue
          }
          return $cmd
        }
        $vvtermPsmuxCommand = Get-VVTermPsmuxCommand
        $vvtermPsmuxInstalled = $null -ne $vvtermPsmuxCommand
        if (-not $vvtermPsmuxInstalled -and (Get-Command winget -ErrorAction SilentlyContinue)) {
          winget install --id marlocarlo.psmux --accept-package-agreements --accept-source-agreements
          $vvtermPsmuxCommand = Get-VVTermPsmuxCommand
          $vvtermPsmuxInstalled = $null -ne $vvtermPsmuxCommand
        }
        if (-not $vvtermPsmuxInstalled -and (Get-Command scoop -ErrorAction SilentlyContinue)) {
          scoop bucket add psmux https://github.com/psmux/scoop-psmux
          scoop install psmux
          $vvtermPsmuxCommand = Get-VVTermPsmuxCommand
          $vvtermPsmuxInstalled = $null -ne $vvtermPsmuxCommand
        }
        if (-not $vvtermPsmuxInstalled -and (Get-Command choco -ErrorAction SilentlyContinue)) {
          choco install psmux -y
          $vvtermPsmuxCommand = Get-VVTermPsmuxCommand
          $vvtermPsmuxInstalled = $null -ne $vvtermPsmuxCommand
        }
        if (-not $vvtermPsmuxInstalled -and (Get-Command cargo -ErrorAction SilentlyContinue)) {
          cargo install psmux
          $vvtermPsmuxCommand = Get-VVTermPsmuxCommand
          $vvtermPsmuxInstalled = $null -ne $vvtermPsmuxCommand
        }
        if ($vvtermPsmuxInstalled) {
        \(indentPowerShell(afterInstall, spaces: 2))
        } else {
          Write-Output 'psmux installation failed or no supported package manager was found.'
        }
        """
        return windowsShellCommand(powerShellScript: script, backend: backend)
    }

    static func windowsConfigPathPowerShellExpression() -> String {
        "$HOME + \(powerShellQuoted("\\.vvterm\\psmux.conf"))"
    }

    private static func windowsConfigDirectoryPowerShellExpression() -> String {
        "$HOME + \(powerShellQuoted("\\.vvterm"))"
    }

}
